arbiter:
  build: arbiter/2.4
  links:
    - poller
    - scheduler
    - reactionner
    - broker
    - receiver
  volumes_from:
    - config
    - data
poller:
  build: poller/2.4
  links:
    - scheduler
  volumes_from:
    - config
    - data
scheduler:
  build: scheduler/2.4
  volumes_from:
    - config
    - data
reactionner:
  build: reactionner/2.4
  links:
    - scheduler
  volumes_from:
    - config
    - data
broker:
  build: broker/2.4
  volumes_from:
    - config
    - data
receiver:
  build: receiver/2.4
  volumes_from:
    - config
    - data

config:
  image: pockost/shinken:2.4-base
  volumes:
    - /etc/shinken
data:
  image: pockost/shinken:2.4-base
  volumes:
    - /var/lib/shinken
